# Generated by Django 3.0.7 on 2020-07-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_auto_20200629_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='player_error',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
