# Generated by Django 3.0.7 on 2020-07-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0009_auto_20200721_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='flop_displayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='river_displayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='turn_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
