# Generated by Django 3.0.7 on 2020-08-30 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0011_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='Table', max_length=25)),
                ('player1', models.CharField(default='none', max_length=25)),
                ('player2', models.CharField(default='none', max_length=25)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('access_code', models.CharField(default='', max_length=25)),
            ],
        ),
    ]
