# Generated by Django 3.0.7 on 2020-06-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20200612_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='access_code',
            field=models.CharField(default='wdeed', max_length=16),
            preserve_default=False,
        ),
    ]
