# Generated by Django 3.0.7 on 2020-06-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_table_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='dealer',
            field=models.CharField(default='none', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='player1',
            field=models.CharField(default='none', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='player1_current_stack',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='player1_last_bet_amount',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='player1_turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='table',
            name='player2',
            field=models.CharField(default='none', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='player2_current_stack',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='player2_last_bet_amount',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='player2_turn',
            field=models.BooleanField(default=False),
        ),
    ]
