# Generated by Django 3.0.7 on 2020-06-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_auto_20200613_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='player1_current_stack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='player1_last_bet_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='player2_current_stack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='player2_last_bet_amount',
            field=models.IntegerField(),
        ),
    ]
